# Generated by Django 4.2.15 on 2024-09-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
